export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const APPEND_LOG = 'APPEND_LOG'

export const UPDATE_TICK = 'UPDATE_TICK'

export const INIT_TICKS = 'INIT_TICKS'

export const UPDATE_POSITION = 'UPDATE_POSITION'

export const UPDATE_ORDER = 'UPDATE_ORDER'

export const UPDATE_TRADE = 'UPDATE_TRADE'

export const UPDATE_CONFIG = 'UPDATE_CONFIG'
